# Cylane config file via .yaml

bot:
  TOKEN: Your token
  EMBED_COLOR: "Your color. Example: #ffffff"
  OWNER_ID: "Your id"
  LANGUAGE: en # You can set it to vi, en, th,...
  LIMIT_TRACK: 50 # The number of tracks you want to limit
  LIMIT_PLAYLIST: 20 # The number of playlist you want to limit

lavalink:
  SPOTIFY:
    # Your spotify id and secret, you can get it from here: https://developer.spotify.com/
    # If you don't have or don't want, you can disable it
    enable: false
    id: a98a98s9a89as98a9s8a98
    secret: a98a98s9a89as98a9s8a98

  DEFAULT: ["yorushika", "yoasobi", "tuyu", "hinkik"]
  
  NP_REALTIME: false # Enable this if you want to use realtime duation in nowplaying command

  LEAVE_TIMEOUT: 100 # The number of leave time you want

  # You can add more lavalink server!
  NODES:
    url: "narco.buses.rocks:2269"
    auth: "glasshost1984"
    secure: false
  SHOUKAKU_OPTIONS: {
    moveOnDisconnect: true,
    resumable: true,
    resumableTimeout: 600,
    reconnectTries: Infinity,
    restTimeout: 3000
  }

features:
  DATABASE:
  # Note: You can't enable all or 2 databases. It will return to JSON database
    JSON:
      enable: true
      path: "./cylane.database.json"
    MONGO_DB:
      enable: false
      # Your mongo_uri, you can get it from here: https://www.mongodb.com/
      uri: mongodb://127.0.0.1:27017/dreamvast
    MYSQL: 
      enable: false
      host: "localhost"
      user: "me"
      password: "secret"
      database: "my_db"
  
  SHARD_SYSTEM: 
    enable: false # If you want to use shard system, change it to `true`
    totalShards: 3 # you can set to every number you want but for save mode, use 'auto' option
    totalClusters: 1 # you can set to every number you want but for save mode, use 'auto' option
    shardsPerClusters: 2
    mode: 'worker' # you can also choose "process"

  MESSAGE_CONTENT:
    enable: true
    prefix: "d!" # The prefix you want
  
  AUTO_DEPLOY: true
  AUTO_REMOVE_DUPLICATE: true
  AUTOFIX_LAVALINK: true # Fix the lavalink server when the current is down

  ALIVE_SERVER:
    enable: false
    port: 3000

  WEBSOCKET:
    enable: false
    port: 8080
    auth: false
    trusted: ['http://localhost:3000']

  # Your id or friend id (disable global command)
  DEV_ID: []