"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const middlewares_1 = require("../../utils/middlewares");
const guilds_1 = require("../../controllers/guilds");
const guilds_2 = require("../../controllers/guilds");
const guilds_3 = require("../../controllers/guilds");
const guilds_4 = require("../../controllers/guilds");
const guilds_5 = require("../../controllers/guilds");
const guilds_6 = require("../../controllers/guilds");
const guilds_7 = require("../../controllers/guilds");
const guilds_8 = require("../../controllers/guilds");
const router = (0, express_1.Router)();
router.get('/', middlewares_1.isAuthenticated, guilds_1.getGuildsController);
router.get('/user', middlewares_1.isAuthenticated, guilds_8.getBotInGuildsController);
router.get('/:id', middlewares_1.isAuthenticated, guilds_1.getGuildController);
router.get('/:id/permissions', middlewares_1.isAuthenticated, guilds_2.getGuildPermissionsController);
router.get('/:id/settings/setup', middlewares_1.isAuthenticated, guilds_5.getGuildReqChannelController);
router.get('/:id/settings/control', middlewares_1.isAuthenticated, guilds_3.getGuildConfigController);
router.post('/:id/settings/control', middlewares_1.isAuthenticated, guilds_7.postGuildControlController);
router.get('/:id/settings/language', middlewares_1.isAuthenticated, guilds_4.getGuildLangController);
router.post(`/:id/settings/language`, middlewares_1.isAuthenticated, guilds_6.postGuildLangController);
exports.default = router;
